name: NPM Publish

on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: "@idamidzin"

      # Check & publish section for project modules

      ## ===================== Begin Auth ===================== ## 
      - name: Check Version Changes for Auth
        id: auth
        uses: EndBug/version-check@v1
        with:
          diff-search: true
          file-name: ./auth/package.json
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Auth
        if: steps.auth.outputs.changed == 'true'
        run: |
          cd ./auth
          npm i
          npm run lint
          npm run test
          npm run build
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ## ===================== End Auth ===================== ##